function(xylem_apply_sanitizer TARGET NAME FLAG)
    if(${NAME})
        if(WIN32 AND CMAKE_C_COMPILER_ID STREQUAL "MSVC")
            target_compile_options(${TARGET} PRIVATE "/fsanitize=${FLAG}")
            target_link_options(${TARGET} PRIVATE "/fsanitize=${FLAG}")
        elseif(UNIX)
            target_compile_options(${TARGET} PRIVATE "-fsanitize=${FLAG}" -fno-omit-frame-pointer)
            target_link_options(${TARGET} PRIVATE "-fsanitize=${FLAG}")
        endif()
    endif()
endfunction()